"""book.yaml, manifest.json, 00_BOOK_INDEX.md, README.md (generated knowledge-base files)."""
from __future__ import annotations
import re
from datetime import datetime, timezone
from pathlib import Path
from . import APP_VERSION, PARSER_VERSION
from .util import atomic_write, write_json, read_json, sha256_file

STATUS_TXT = {"NOT_STARTED": "Not started", "PROCESSING": "Processing", "PARTIAL": "Partial", "COMPLETED": "Completed",
              "COMPLETED_WITH_WARNINGS": "Completed with warnings", "REVIEW_REQUIRED": "Review required", "FAILED": "Failed"}


def _q(s): return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_all(project):
    d = project.data
    ov = project.overview()
    atomic_write(project.root / "book.yaml", "\n".join([
        f"title: {_q(d['title'])}", f"edition: {_q(d['edition'])}", f"author: {_q(d.get('author', ''))}",
        f"source_file: {_q(d['source_name'])}", f"source_sha256: {_q(d['source_sha256'])}", f"pages: {d['pages']}",
        f"slug: {_q(d['slug'])}", f"parser_version: {_q(PARSER_VERSION)}", f"app_version: {_q(APP_VERSION)}",
        "chapters:", *[f"  - number: {c['number']}\n    title: {_q(c['title'])}\n    pages: {_q(str(c['start_page']) + '-' + str(c['end_page']))}\n    status: {c['status']}" for c in ov["chapters"]]]) + "\n")
    rows = ["| Chapter | Title | Specialty | Source Pages | Markdown File | Conversion Status |", "|---|---|---|---|---|---|"]
    for c in ov["chapters"]:
        link = f"[{Path(c['markdown_file']).name}]({c['markdown_file']})" if c["markdown_file"] else "—"
        title = f"[{c['title']}]({c['markdown_file']})" if c["markdown_file"] else c["title"]
        rows.append(f"| {c['number']} | {title} | {c.get('specialty', '')} | {c['start_page']}–{c['end_page']} | {link} | {STATUS_TXT.get(c['status'], c['status'])} |")
    atomic_write(project.root / "00_BOOK_INDEX.md", f"# {d['title']}" + (f" — Edition {d['edition']}" if d['edition'] else "") + "\n\n" + "\n".join(rows) + "\n")
    atomic_write(project.root / "README.md", readme(project))
    chfiles, assets, reports, tables = [], [], [], []
    for c in ov["chapters"]:
        if c["markdown_file"]:
            chfiles.append({"chapter": c["number"], "file": c["markdown_file"], "sha256": project.progress(c["number"]).get("markdown_sha256", ""), "status": c["status"]})
    for f in sorted((project.root / "assets").rglob("*.png")):
        assets.append(str(f.relative_to(project.root)))
    for f in sorted((project.root / "reports").glob("*.md")):
        reports.append(str(f.relative_to(project.root)))
    for f in sorted((project.root / "tables").rglob("*.md")):
        tables.append(str(f.relative_to(project.root)))
    write_json(project.root / "manifest.json", {
        "title": d["title"], "edition": d["edition"], "source_file": d["source_name"], "source_sha256": d["source_sha256"],
        "pages": d["pages"], "created": d["created"], "updated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "software_version": APP_VERSION, "parser_version": PARSER_VERSION, "chapters": [{**{k: c[k] for k in ("number", "title", "start_page", "end_page", "status")}} for c in ov["chapters"]],
        "chapter_files": chfiles, "assets": assets, "tables": tables, "reports": reports,
        "indexes": [str(f.relative_to(project.root)) for f in sorted((project.root / "indexes").glob("*.md"))]})


def readme(project) -> str:
    d = project.data
    return f"""# {d['title']} — Markdown Knowledge Base

Generated by MD-PDF (mdkb {APP_VERSION}) from `{d['source_name']}`.

- **Source book:** {d['title']}{' (edition ' + d['edition'] + ')' if d['edition'] else ''}
- **Source SHA-256:** `{d['source_sha256']}`
- **Conversion date:** {datetime.now(timezone.utc).date().isoformat()}

## Folder structure
```
00_BOOK_INDEX.md   chapter list with status        book.yaml / manifest.json  metadata
chapters/          one Markdown file per chapter   assets/images/ch_NNN/      extracted figures
tables/ch_NNN/     large tables (separate files)   source_maps/ch_NNN.json    block -> PDF page/bbox
indexes/           generated navigation indexes    rag/chunks.jsonl           RAG chunks
reports/           per-chapter conversion reports  metadata/                  unresolved refs, conversion memory
```

## Conventions
- **Page markers:** `<!-- source_page: N -->` marks where PDF page N starts. Hidden in rendered Markdown; shown as `[Trang gốc: N]` in the app's source/debug mode.
- **Tables:** simple tables are GFM tables. Tables with merged cells or multi-row headers are embedded HTML. Tables with more than 40 rows live in `tables/ch_NNN/` and are linked from the chapter.
- **Figures:** PNG files under `assets/images/ch_NNN/`, referenced by relative path. Captions are preserved verbatim.
- **Citations/references:** in-text markers and the reference list are preserved with original numbering; reference entries carry `<a id="ref-N">` anchors.
- **Section IDs:** stable IDs in `<!-- section_id: ... -->` comments and source maps.
- **Uncertain text:** `<!-- UNCERTAIN: ... -->`. Nothing is guessed.

## Generated indexes — disclaimer
Files in `indexes/` are *generated navigation aids — not part of the original textbook*. The textbook text lives only in `chapters/`.
The text is source-faithful English; it is not summarised, translated or corrected.

## Using this folder
- **Obsidian:** open the folder as a vault. Standard Markdown links work; no plugin required.
- **VS Code:** open the folder; use Markdown preview. Search with Ctrl/Cmd+Shift+F.
- **GitHub:** push the folder; relative links and images render.
- The knowledge base needs no app: everything is plain Markdown/JSON. The `.mdkb/` folder is only an app cache and can be deleted.
"""
